name: Deploy to Vercel (Production Manual)

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci

      - name: Deploy via Vercel CLI
        run: |
          npm install -g vercel
          vercel --prod \
          --token=${{ secrets.VERCEL_TOKEN }} \
          --yes \
          --confirm
